name: build_apk

# action事件触发
on:
    workflow_dispatch:
    push:
        # push tag时触发
        tags:
            - v*

# 可以有多个jobs
jobs:
    build_apk:
        # 运行环境 ubuntu-latest window-latest mac-latest
        runs-on: ubuntu-latest

        # 每个jobs中可以有多个steps
        steps:
            - name: 拉取代码
              uses: actions/checkout@v3

            - name: 构建Java环境
              uses: actions/setup-java@v3
              with:
                  distribution: "zulu"
                  java-version: "17"
                  token: ${{secrets.GIT_TOKEN}}

            - name: 检查缓存
              uses: actions/cache@v4
              id: cache-flutter
              with:
                  path: /root/flutter-sdk # Flutter SDK 的路径
                  key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}

            - name: 安装Flutter
              if: steps.cache-flutter.outputs.cache-hit != 'true'
              uses: subosito/flutter-action@v2
              with:
                  flutter-version: 3.27.1
                  channel: stable

            - name: 下载项目依赖
              run: flutter pub get

            - name: 解码生成 jks
              run: echo $KEYSTORE_BASE64 | base64 -di > android/app/keystore.jks
              env:
                  KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

            - name: 修改错误kotlin
              run: sed -i '13s/^.*$/jvmTarget = '\''1.8'\''/' "${PUB_CACHE}/hosted/pub.flutter-io.cn/shared_preferences_android-2.4.7/android/build.gradle"

            - name: flutter build apk --release
              # 对应 android/app/build.gradle signingConfigs中的配置项
              run: flutter build apk --release --split-per-abi
              env:
                  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
                  KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
                  KEY_PASSWORD: ${{ secrets.KEY_PASSWORD}}

            - name: 发布apk
              uses: ncipollo/release-action@v1.5.0
              with:
                  artifacts: "build/app/outputs/apk/release/*.apk"
                  token: ${{ secrets.RELEASE_TOKEN }}
